"""End-to-end tests for the Prometheus `/metrics` endpoint.

Scope
-----
* Validates the instrumentator wiring (``setup_metrics``) mounts
  ``/metrics`` when ``PROMETHEUS_ENABLED`` is true and omits it when
  false.
* Confirms the exposition payload is valid Prometheus text format:
  ``HELP`` / ``TYPE`` comments plus at least one ``http_request*``
  sample generated by the preceding request.
* Ensures the endpoint stays dependency-free (no DB / Redis). The app
  is built with ``DB_AUTO_MIGRATE=false`` and no database is touched
  by the test.

Each test constructs its **own** FastAPI instance so the global
Prometheus ``REGISTRY`` is isolated from the rest of the suite — tests
in this module are the only ones that turn instrumentation on.
"""

from __future__ import annotations

from collections.abc import Iterator

import pytest
from fastapi.testclient import TestClient

from app.core.config import Settings, get_settings
from app.main import create_app


@pytest.fixture
def enabled_client() -> Iterator[TestClient]:
    """TestClient against an app with Prometheus instrumentation on."""
    get_settings.cache_clear()
    settings = Settings(
        APP_ENV="test",
        DEBUG="true",
        LOG_LEVEL="WARNING",
        API_PREFIX="/api/v1",
        API_CORS_ORIGINS="",
        DB_AUTO_MIGRATE="false",
        PROMETHEUS_ENABLED="true",
        PROMETHEUS_PATH="/metrics",
    )
    app = create_app(settings)
    app.dependency_overrides[get_settings] = lambda: settings
    with TestClient(app) as tc:
        yield tc
    app.dependency_overrides.clear()
    get_settings.cache_clear()


@pytest.fixture
def disabled_client() -> Iterator[TestClient]:
    """TestClient against an app with Prometheus instrumentation off."""
    get_settings.cache_clear()
    settings = Settings(
        APP_ENV="test",
        DEBUG="true",
        LOG_LEVEL="WARNING",
        API_PREFIX="/api/v1",
        API_CORS_ORIGINS="",
        DB_AUTO_MIGRATE="false",
        PROMETHEUS_ENABLED="false",
    )
    app = create_app(settings)
    app.dependency_overrides[get_settings] = lambda: settings
    with TestClient(app) as tc:
        yield tc
    app.dependency_overrides.clear()
    get_settings.cache_clear()


def test_metrics_endpoint_returns_prometheus_text(enabled_client: TestClient) -> None:
    # Hit an instrumented endpoint first so we actually have samples
    # to emit. `/health` is explicitly excluded from instrumentation,
    # so we pick a real v1 route instead.
    enabled_client.get("/api/v1/version")

    resp = enabled_client.get("/metrics")
    assert resp.status_code == 200

    # The content type for the Prometheus text exposition format.
    ctype = resp.headers.get("content-type", "")
    assert "text/plain" in ctype

    body = resp.text
    # Exposition format markers — mandatory for valid output.
    assert "# HELP" in body
    assert "# TYPE" in body
    # Instrumentator always emits http_request_* metrics.
    assert "http_requests_total" in body or "http_request_duration_seconds" in body


def test_metrics_endpoint_excludes_health_and_metrics_itself(
    enabled_client: TestClient,
) -> None:
    # Call endpoints that are configured to be excluded from scraping.
    enabled_client.get("/health")
    enabled_client.get("/metrics")

    resp = enabled_client.get("/metrics")
    body = resp.text
    # The excluded handlers must not contribute to `http_requests_total`.
    # A naive `/health` hit would otherwise surface as
    # `handler="/health"` in the output.
    assert 'handler="/health"' not in body
    assert 'handler="/metrics"' not in body


def test_metrics_endpoint_disabled_returns_404(disabled_client: TestClient) -> None:
    resp = disabled_client.get("/metrics")
    assert resp.status_code == 404


def test_metrics_endpoint_does_not_require_database(enabled_client: TestClient) -> None:
    # Regression guard: `/metrics` is scraped every 15s and MUST NOT
    # lazily open a DB session or a Redis connection. Hitting it on a
    # freshly-booted app (no DB wired) should succeed.
    resp = enabled_client.get("/metrics")
    assert resp.status_code == 200
    # The body is a plain text exposition, never a JSON error envelope.
    assert "code" not in resp.text or "HELP" in resp.text


def test_setup_metrics_is_idempotent() -> None:
    """Calling ``setup_metrics`` twice should not double-register."""
    from app.observability import setup_metrics

    get_settings.cache_clear()
    settings = Settings(
        APP_ENV="test",
        DEBUG="true",
        LOG_LEVEL="WARNING",
        API_PREFIX="/api/v1",
        API_CORS_ORIGINS="",
        DB_AUTO_MIGRATE="false",
        PROMETHEUS_ENABLED="true",
    )
    app = create_app(settings)
    # `create_app` already called setup_metrics once; a second call
    # should be a no-op and return the cached instrumentator.
    first = getattr(app.state, "instrumentator", None)
    second = setup_metrics(app, settings)
    assert first is not None
    assert second is first
    get_settings.cache_clear()
