"""ORM models package.

The declarative ``Base`` lives here and acts as the registry that
Alembic's autogenerate inspects to diff the live database against
the Python models.

Importing this package (or any sub-module) is sufficient to register
all models with ``Base.metadata``. Alembic's ``env.py`` already imports
this package so every model is visible at migration time.

Models added in task 1.2
------------------------
* ``Fund``             — ``funds`` table (standard PostgreSQL relation)
* ``FundNav``          — ``fund_nav`` TimescaleDB hypertable
* ``FundHolding``      — ``fund_holdings`` quarterly snapshot table
* ``FundDividend``     — ``fund_dividends`` corporate-action table
* ``FundAnnouncement`` — ``fund_announcements`` table
* ``FundFee``          — ``fund_fees`` tiered fee schedule table
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Project-wide naming convention for constraints and indexes.
# Alembic uses ``MetaData.naming_convention`` to emit deterministic
# constraint names in autogenerated migrations — without this, names
# would drift between developer machines and production deployments.
# See: https://alembic.sqlalchemy.org/en/latest/naming.html
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every ORM model in the project.

    We subclass rather than reuse SQLAlchemy's factory so we can attach
    project-wide conventions (naming conventions, mixins, etc.) without
    touching every model file.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# ---------------------------------------------------------------------------
# Import all concrete models so they register with Base.metadata.
# The order here does not matter for SQLAlchemy; Alembic will sort
# dependencies automatically when generating migrations.
# ---------------------------------------------------------------------------
from app.data.models.fund_announcements import FundAnnouncement  # noqa: E402, F401
from app.data.models.fund_dividends import FundDividend  # noqa: E402, F401
from app.data.models.fund_fees import FundFee  # noqa: E402, F401
from app.data.models.fund_holdings import FundHolding  # noqa: E402, F401
from app.data.models.fund_nav import FundNav  # noqa: E402, F401
from app.data.models.fund_ranking import FundRanking  # noqa: E402, F401
from app.data.models.funds import Fund  # noqa: E402, F401
from app.data.models.advisor_results import AdvisorResult  # noqa: E402, F401
from app.data.models.advisor_positions import AdvisorPosition  # noqa: E402, F401
from app.data.models.advisor_position_imports import AdvisorPositionImport  # noqa: E402, F401
from app.data.models.advisor_execution_records import AdvisorExecutionRecord  # noqa: E402, F401
from app.data.models.advisor_reminders import AdvisorReminder  # noqa: E402, F401
from app.data.models.advisor_reminder_preferences import AdvisorReminderPreference  # noqa: E402, F401
from app.data.models.advisor_user_learning_profiles import AdvisorUserLearningProfile  # noqa: E402, F401
from app.data.models.advisor_learned_params_versions import AdvisorLearnedParamsVersion  # noqa: E402, F401
from app.data.models.advisor_oos_snapshots import AdvisorOOSSnapshot  # noqa: E402, F401
from app.data.models.advisor_parameter_sets import AdvisorParameterSet  # noqa: E402, F401
from app.data.models.strategies import Strategy  # noqa: E402, F401
from app.data.models.backtests import BacktestEquity, BacktestRun, BacktestTrade  # noqa: E402, F401
from app.data.models.benchmark import BenchmarkNav  # noqa: E402, F401
from app.data.models.signals import Signal  # noqa: E402, F401
from app.data.models.llm_calls import LLMCall  # noqa: E402, F401
from app.data.models.simulations import SimulationRun  # noqa: E402, F401
from app.data.models.index_valuation import IndexValuation  # noqa: E402, F401

__all__ = [
    "Base",
    "NAMING_CONVENTION",
    "Fund",
    "FundNav",
    "FundHolding",
    "FundDividend",
    "FundAnnouncement",
    "FundFee",
    "FundRanking",
    "AdvisorResult",
    "AdvisorPosition",
    "AdvisorPositionImport",
    "AdvisorExecutionRecord",
    "AdvisorReminder",
    "AdvisorReminderPreference",
    "AdvisorUserLearningProfile",
    "AdvisorLearnedParamsVersion",
    "AdvisorOOSSnapshot",
    "AdvisorParameterSet",
    "Strategy",
    "BacktestRun",
    "BacktestEquity",
    "BacktestTrade",
    "BenchmarkNav",
    "Signal",
    "LLMCall",
    "SimulationRun",
    "IndexValuation",
]
