"""ORM model for persisted advisor learned-parameter versions.

Stores each daily learned-parameter snapshot generated by the feedback
learner so live analysis can load the latest version while historical
replay can resolve the newest snapshot that does not exceed a requested
``as_of_date``.
"""

from __future__ import annotations

from datetime import date, datetime

from sqlalchemy import BigInteger, Date, DateTime, Float, Integer, JSON, String, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.data.models import Base

_JsonType = JSON().with_variant(JSONB, "postgresql")
_IdType = Integer().with_variant(BigInteger, "postgresql")


class AdvisorLearnedParamsVersion(Base):
    """Persistent representation of one learned-parameter version."""

    __tablename__ = "advisor_learned_params_versions"
    __table_args__ = (
        UniqueConstraint(
            "learn_date",
            name="uq_advisor_learned_params_versions_learn_date",
        ),
    )

    id: Mapped[int] = mapped_column(
        _IdType,
        primary_key=True,
        autoincrement=True,
        comment="Learned-parameter version unique identifier",
    )
    learn_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        index=True,
        comment="Logical date this learned-parameter version applies to",
    )
    engine_version: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="5.0",
        comment="Advisor engine version tag",
    )
    sample_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of tracked samples used for learning",
    )
    confidence: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
        comment="Confidence score of the learned result",
    )
    factor_ics: Mapped[dict | None] = mapped_column(
        _JsonType,
        nullable=True,
        comment="Per-factor IC snapshot",
    )
    weight_multipliers: Mapped[dict | None] = mapped_column(
        _JsonType,
        nullable=True,
        comment="Learned weight multipliers",
    )
    threshold_adjustment: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
        comment="Learned threshold adjustment",
    )
    momentum_discount_calibrated: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Learned momentum discount calibration",
    )
    adjustments_log: Mapped[list | None] = mapped_column(
        _JsonType,
        nullable=True,
        comment="Adjustment log generated by feedback learner",
    )
    config_hash: Mapped[str | None] = mapped_column(
        String(64),
        nullable=True,
        index=True,
        comment="Stable hash of the full learned-parameter payload",
    )
    gate_status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="not_evaluated",
        index=True,
        comment="Parameter release gate status: approved/shadow_only/blocked/not_evaluated",
    )
    gate_action: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="shadow_only",
        comment="Gate action: allow_default/shadow_only/block_default",
    )
    gate_reason: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Human readable parameter release gate reason",
    )
    gate_checked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when the parameter gate was evaluated",
    )
    gate_metrics: Mapped[dict | None] = mapped_column(
        _JsonType,
        nullable=True,
        comment="OOS/PBO metrics used by the parameter release gate",
    )
    created_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        server_default=func.now(),
        comment="Creation timestamp (UTC)",
    )
    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Last update timestamp (UTC)",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<AdvisorLearnedParamsVersion id={self.id!r} "
            f"learn_date={self.learn_date!r} version={self.engine_version!r}>"
        )
