"""ORM model for the ``signals`` table.

Stores trading signals generated by subscribed strategies. Each signal
represents a strategy's recommendation for a specific fund on a given
trading day.

Requirements: 8.2
"""

from __future__ import annotations

from datetime import date, datetime

from sqlalchemy import BigInteger, Date, DateTime, Integer, JSON, Numeric, String, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.data.models import Base

# Use JSONB on PostgreSQL, fall back to JSON on other dialects (e.g. SQLite in tests)
_JsonType = JSON().with_variant(JSONB, "postgresql")

# BigInteger on PostgreSQL (BIGSERIAL), Integer on SQLite (for autoincrement support)
_IdType = Integer().with_variant(BigInteger, "postgresql")


class Signal(Base):
    """Persistent representation of a strategy-generated trading signal.

    Each row represents one signal (buy/sell/hold recommendation) for a
    specific fund, generated by a specific strategy on a given date.
    """

    __tablename__ = "signals"
    __table_args__ = (
        UniqueConstraint(
            "strategy_id",
            "fund_code",
            "signal_date",
            "direction",
            name="uq_signals_strategy_fund_date_direction",
        ),
    )

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[int] = mapped_column(
        _IdType,
        primary_key=True,
        autoincrement=True,
        comment="Signal unique identifier",
    )

    # ------------------------------------------------------------------
    # Core fields
    # ------------------------------------------------------------------
    strategy_id: Mapped[int] = mapped_column(
        _IdType,
        nullable=False,
        index=True,
        comment="Reference to strategies.id",
    )
    strategy_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Strategy display name (denormalized for quick access)",
    )
    fund_code: Mapped[str] = mapped_column(
        String(10),
        nullable=False,
        index=True,
        comment="Fund code this signal applies to",
    )
    signal_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        index=True,
        comment="Date the signal was generated for",
    )
    direction: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Signal direction: subscribe/redeem/hold",
    )
    strength: Mapped[float | None] = mapped_column(
        Numeric(8, 4),
        nullable=True,
        comment="Signal strength/confidence (0.0 to 1.0)",
    )
    target_weight: Mapped[float | None] = mapped_column(
        Numeric(8, 4),
        nullable=True,
        comment="Target portfolio weight for this fund",
    )
    amount: Mapped[float | None] = mapped_column(
        Numeric(20, 2),
        nullable=True,
        comment="Suggested trade amount (for subscribe)",
    )
    shares: Mapped[float | None] = mapped_column(
        Numeric(20, 4),
        nullable=True,
        comment="Suggested trade shares (for redeem)",
    )
    reason: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
        comment="Human-readable reason for the signal",
    )
    metadata_json: Mapped[dict | None] = mapped_column(
        _JsonType,
        nullable=True,
        comment="Additional signal metadata (strategy params, context, etc.)",
    )
    notified: Mapped[bool] = mapped_column(
        default=False,
        comment="Whether notification has been sent for this signal",
    )
    created_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        server_default=func.now(),
        comment="Creation timestamp (UTC)",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<Signal id={self.id!r} strategy={self.strategy_name!r} "
            f"fund={self.fund_code!r} direction={self.direction!r} "
            f"date={self.signal_date!r}>"
        )
