"""add advisor learned versions and execution audit

Revision ID: d1e2f3a4b5c6
Revises: c9d0e1f2a3b4
Create Date: 2026-05-27 00:00:00.000000+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "d1e2f3a4b5c6"
down_revision: Union[str, Sequence[str], None] = "c9d0e1f2a3b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_json_type = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    op.create_table(
        "advisor_learned_params_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="Learned-parameter version unique identifier"),
        sa.Column("learn_date", sa.Date(), nullable=False, comment="Logical date this learned-parameter version applies to"),
        sa.Column("engine_version", sa.String(length=20), nullable=False, server_default="5.0", comment="Advisor engine version tag"),
        sa.Column("sample_count", sa.Integer(), nullable=False, server_default="0", comment="Number of tracked samples used for learning"),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0", comment="Confidence score of the learned result"),
        sa.Column("factor_ics", _json_type, nullable=True, comment="Per-factor IC snapshot"),
        sa.Column("weight_multipliers", _json_type, nullable=True, comment="Learned weight multipliers"),
        sa.Column("threshold_adjustment", sa.Float(), nullable=False, server_default="0", comment="Learned threshold adjustment"),
        sa.Column("momentum_discount_calibrated", sa.Float(), nullable=True, comment="Learned momentum discount calibration"),
        sa.Column("adjustments_log", _json_type, nullable=True, comment="Adjustment log generated by feedback learner"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True, comment="Creation timestamp (UTC)"),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True, comment="Last update timestamp (UTC)"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisor_learned_params_versions")),
        sa.UniqueConstraint("learn_date", name="uq_advisor_learned_params_versions_learn_date"),
    )
    op.create_index(op.f("ix_advisor_learned_params_versions_learn_date"), "advisor_learned_params_versions", ["learn_date"], unique=False)

    op.add_column(
        "advisor_results",
        sa.Column(
            "learned_params_version_id",
            sa.BigInteger(),
            nullable=True,
            comment="Resolved learned-parameter version id used during analysis",
        ),
    )
    op.add_column(
        "advisor_results",
        sa.Column(
            "source_result_id",
            sa.BigInteger(),
            nullable=True,
            comment="Source advisor result id when generated from refresh or replay",
        ),
    )
    op.add_column(
        "advisor_results",
        sa.Column(
            "analysis_mode",
            sa.String(length=30),
            nullable=True,
            comment="Execution mode: live/portfolio/history_refresh/nightly/walk_forward",
        ),
    )
    op.add_column(
        "advisor_results",
        sa.Column(
            "execution_context",
            _json_type,
            nullable=True,
            comment="Serialized execution context and audit metadata",
        ),
    )
    op.create_index(op.f("ix_advisor_results_learned_params_version_id"), "advisor_results", ["learned_params_version_id"], unique=False)
    op.create_index(op.f("ix_advisor_results_source_result_id"), "advisor_results", ["source_result_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_advisor_results_source_result_id"), table_name="advisor_results")
    op.drop_index(op.f("ix_advisor_results_learned_params_version_id"), table_name="advisor_results")
    op.drop_column("advisor_results", "execution_context")
    op.drop_column("advisor_results", "analysis_mode")
    op.drop_column("advisor_results", "source_result_id")
    op.drop_column("advisor_results", "learned_params_version_id")

    op.drop_index(op.f("ix_advisor_learned_params_versions_learn_date"), table_name="advisor_learned_params_versions")
    op.drop_table("advisor_learned_params_versions")
